# Prometheus 서버에 수집된 지표를 시각화하는 Grafana 서버를 실행합니다.

services:
  grafana:
    # 11.1.4 은 정상 작동을 검증한 버전입니다. 이후 버전을 사용해도 될 것으로 예상합니다.
    image: grafana/grafana-enterprise:11.1.4
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./etc/grafana:/etc/grafana:ro # 호스트의 설정 디렉토리 읽기 전용으로 마운트
      - grafana_data:/var/lib/grafana # Grafana 데이터 저장소
    ports:
      - '3000:3000'
    network_mode: 'host'

volumes:
  grafana_data:
    name: grafana_data
