# Provisioning Data Sources
# Ref - https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources

apiVersion: 1

datasources:
  - name: perf-testing
    uid: perf-testing-datasource-1
    type: prometheus
    access: proxy
    url: http://localhost:9090
    basicAuth: false
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 5s
    editable: true
