# node-exporter 를 실행하기 위한 docker-compose 설정파일입니다.
#
# 참고자료
# - https://github.com/prometheus/node_exporter

services:
  node_exporter:
    # v1.8.2 은 정상 작동을 검증한 버전입니다. 이후 버전을 사용해도 될 것으로 예상합니다.
    image: prom/node-exporter:v1.8.2
    container_name: node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
    ports:
      - '9100:9100'
    network_mode: 'host'
